export const clientsData = [
  {
    id: 1,
    title: "OYO",
    logo: "/images/brands/oyo-logo.svg",
    link: "https://oyorooms.com/",
    invert: false,
  },
  {
    id: 2,
    title: "Best Western",
    logo: "images/brands/best-western-logo.svg",
    link: "https://www.bestwestern.com/",
    invert: true,
  },
  {
    id: 3,
    title: "Golden Tulip Hotels",
    logo: "/images/brands/golden-tulip-logo.svg",
    link: "https://goldentulip.com/",
    invert: true,
  },
  {
    id: 4,
    title: "Mercure Hotels",
    logo: "/images/brands/mercure-hotels-vector-logo.svg",
    link: "https://mercure.accor.com/",
    invert: true,
  },
  {
    id: 5,
    title: "Holiday Inn",
    logo: "/images/brands/holiday-inn-logo.svg",
    link: "https://www.ihg.com/holidayinn/",
    invert: false,
  },
  {
    id: 6,
    title: "My Property Host",
    logo: "/images/brands/mypropertyhost.svg",
    link: "https://www.mypropertyhost.com/",
    invert: false,
  },
  {
    id: 7,
    title: "Opulent Living",
    logo: "/images/brands/opulent-living.svg",
    link: "https://opulentliving.co/",
    invert: true,
  },
  {
    id: 8,
    title: "UR STAY",
    logo: "/images/brands/ur-stay-white.svg",
    link: "https://urstay.co.uk/",
    invert: false,
  },
];
